# -*- coding: utf-8 -*-
"""meeting minutes generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17KfgGgCc7kMePPbWm2jEUTV3kwaHHru_
"""

#================================
#Meeting Minutes Generator
#================================
import pandas as pd
from datetime import datetime
print("MEETINE MINUTES GENERATOR\n")
#User Inputs
meeting_title = input("Enter meeting title: ")
date = input("Enter meeting date (DD-MM-YYYY): ")
time = input("Enter meeting time: ")
participants = input("Enter participants (comma seperated): ")
agenda = input("Enter agenda points (comma seperated): ")
decision = input("Enter decision taken (comma seperated): ")
action_items = input("Enter action items (comma seperated): ")
prepared_by = input("Enter prepared by:")
# process inputs
participants_list = [p.strip() for p in participants.split(",") if p.strip]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decision_list = [d.strip() for d in decision.split(",") if d.strip()]
actions_list = [a.strip() for a in action_items.split(",") if a.strip()]
# create stuctured meeting minutes
minutes = {
    "Meeting Title": meeting_title,
    "Date": date,
    "Time": time,
    "participants": ", ".join(participants_list),
    "Agenda": ";".join(agenda_list),
    "Decision Taken": "; ".join(decision_list),
    "Action Items": "; ".join(actions_list),
    "Prepared By": prepared_by,
    "Generated On": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
}
# convert to DataFrame
df = pd.DataFrame(list(minutes.items()), columns=["Field", "Details"])
print("\n Meeting Minutes Generated Successfully\n")
display(df)
# Save as csv
df.to_csv("meeting_minutes.csv", index=False)
print("\n File saved as meeting_minutes,csv")