# -*- coding: utf-8 -*-
"""program productivity

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1okZcF3N_O_wQ3i48RpSp0eW7BVpe5ZDd
"""

!pip install transformers torch pandas
from transformers import pipeline
import pandas as pd

# load sentiment analysis model.
sentiment = pipeline("sentiment-analysis")
# sample product review (you can change only this text later)
reviews = """The laptop starts quickly and works smoothely for daily tasks.
The screen quality is clear and good for watching videos.
Battery backup is average and needs charging often.
The fan makes noise when many apps are running.
Ovwrall, it is agood laptop for students but not for gamming.
"""
# split review into sentences
sentences = reviews.split(".")
pros = []
cons = []
for s in sentences:
  s = s.strip()
  if s == "":
    continue
  result = sentiment(s)[0]
  if result["label"] == "POSITIVE":
    pros.append(s)
  elif result["label"] == "NEGATIVE":
    cons.append(s)
# take only 2 pros and 2 cons
pros = pros[:2]
cons = cons[:2]
# create table
df = pd.DataFrame({
    "pros": pros,
    "cons": cons
})
df