# -*- coding: utf-8 -*-
"""similarity project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWR95IzF2DTQkxsTb_8F_W66jQnEPQMB
"""

from sentence_transformers import SentenceTransformer, util
# load the model
model = SentenceTransformer('all-MiniLM-L6-V2')
# Take input from user
text1 = input("Enter Text 1:")
text2 = input("Enter Text 2:")
# convert text to Embedding
embedding1=model.encode(text1)
embedding2=model.encode(text2)
#calculate similarity
similarity = util.cos_sim(embedding1,embedding2)
# show result
print("\nsimilarity score:",round(float(similarity),2))
if similarity>0.75:
  print("similarity Level:High")
elif similarity >0.4:
  print("similarity Level:Medium")
else:
  print("similarity Level:Low")