# -*- coding: utf-8 -*-
"""Text generation code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yb2NG1gW60T-GJRr7KVJdxSM9Gwa4EC9
"""

!pip install transformers torch

from transformers import pipeline
# load text generation model(GenAI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)
# input prompt
prompt = "Artificial Intilligence in finance will"
# Generate text
result = generator(prompt,max_length=50,num_return_sequences=1)
print("AI Generated Text:")
print(result[0]['generated_text'])

